events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            # app - это имя сервиса твоего Go-приложения в docker-compose,
            # 8080 - порт, на котором он слушает
            proxy_pass http://app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}