version: '3'

vars:
  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GOLANGCI_LINT_VERSION: 'v1.64.8'

tasks:
  install-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    cmds:
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          mkdir -p {{.BIN_DIR}}
          echo "📦 Устанавливаем golangci-lint..."
          GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}

  lint:
    desc: "Запускает линтер для проекта"
    deps: [ install-lint ]
    cmds:
      - '{{.GOLANGCI_LINT}} run ./... --timeout=3m'

  test:
    desc: "Запускает юнит-тесты"
    cmds:
      - go test -v ./...

  up:
    desc: "Поднять всю инфраструктуру"
    cmds:
      - docker-compose up -d --build

  down:
    desc: "Убить контейнеры и очистить вольюмы"
    cmds:
      - docker-compose down -v
